# Generated by Django 3.1.2 on 2020-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
