# Generated by Django 3.1.2 on 2020-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_prodect_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
